ifndef VERBOSE
.SILENT:
endif
# This hides all output unless call includes VERBOSE=1. So 
# if you use "make up VERBOSE=1" it will display all output.
PROJECT_DIR := $(shell pwd)
DATE_NOW := $(shell date -u +"%Y-%m-%dT%H:%M:%SZ")
FILE_SAFE_DATE_NOW := $(shell date -u +"%Y-%m-%dT%H-%M-%SZ")